version: '3.9'

services:
  db:
    image: postgis/postgis:14-3.3
    container_name: sismos-db
    environment:
      POSTGRES_DB: sismos
      POSTGRES_USER: sismos
      POSTGRES_PASSWORD: sismos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile      
    container_name: sismos-backend
    command: /app/start.sh        
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=sismos
      - DB_USER=sismos
      - DB_PASSWORD=sismos
      - DB_HOST=db
      - DB_PORT=5432

  frontend:
    build:
      context: ./frontend/sismos-mapa
      dockerfile: Dockerfile
      args:
        # IMPORTANTE: usar localhost, accesible desde el navegador
        - VITE_API_BASE_URL=http://localhost:8000
    container_name: sismos-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data: